services:
  - type: web
    name: proyecto-spring
    env: java
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/Proyecto-0.0.1-SNAPSHOT.jar"
    plan: free
    region: oregon
