#{"id":"33471","variant":"standard","title":"render.yaml para Deploy de API Spring Boot con Docker"}

services:
  - type: web
    name: api-oficios
    runtime: docker
    repo: https://github.com/[TU_USUARIO]/[TU_REPO].git
    plan: free
    autoDeploy: true

    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d4jav2vdiees738kmlq0-a.oregon-postgres.render.com/oficiosdb_5ivz

      - key: SPRING_DATASOURCE_USERNAME
        value: root

      - key: SPRING_DATASOURCE_PASSWORD
        value: Bn1glkTfqBqJRfNlhGHPl3iMZIixju3L

      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

      - key: SPRING_JPA_SHOW_SQL
        value: "false"

      - key: PORT
        value: "8080"
